// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: recommendation.proto

package com.mindspore.ide.toolkit.protomessage;

public final class CodeCompletionProto {
  private CodeCompletionProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_CompleteRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_CompleteRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_CompleteReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_CompleteReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_ResultEntries_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_ResultEntries_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_ResultEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_ResultEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\024recommendation.proto\022\005proto\"@\n\017Complet" +
      "eRequest\022\016\n\006prefix\030\001 \001(\t\022\016\n\006before\030\002 \001(\t" +
      "\022\r\n\005after\030\003 \001(\t\"J\n\rCompleteReply\022\022\n\nold_" +
      "prefix\030\001 \001(\t\022%\n\007results\030\002 \001(\0132\024.proto.Re" +
      "sultEntries\"8\n\rResultEntries\022\'\n\013resultEn" +
      "try\030\001 \003(\0132\022.proto.ResultEntry\"2\n\013ResultE" +
      "ntry\022\022\n\nnew_prefix\030\001 \001(\t\022\017\n\007details\030\002 \001(" +
      "\t2N\n\007Greeter\022C\n\021getRecommendation\022\026.prot" +
      "o.CompleteRequest\032\024.proto.CompleteReply\"" +
      "\000B?\n&com.mindspore.ide.toolkit.protomess" +
      "ageB\023CodeCompletionProtoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_proto_CompleteRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_CompleteRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_CompleteRequest_descriptor,
        new String[] { "Prefix", "Before", "After", });
    internal_static_proto_CompleteReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_proto_CompleteReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_CompleteReply_descriptor,
        new String[] { "OldPrefix", "Results", });
    internal_static_proto_ResultEntries_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_proto_ResultEntries_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_ResultEntries_descriptor,
        new String[] { "ResultEntry", });
    internal_static_proto_ResultEntry_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_proto_ResultEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_ResultEntry_descriptor,
        new String[] { "NewPrefix", "Details", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
