// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: recommendation.proto

package com.mindspore.ide.toolkit.protomessage;

public interface CompleteReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.CompleteReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string old_prefix = 1;</code>
   */
  String getOldPrefix();
  /**
   * <code>string old_prefix = 1;</code>
   */
  com.google.protobuf.ByteString
      getOldPrefixBytes();

  /**
   * <code>.proto.ResultEntries results = 2;</code>
   */
  boolean hasResults();
  /**
   * <code>.proto.ResultEntries results = 2;</code>
   */
  ResultEntries getResults();
  /**
   * <code>.proto.ResultEntries results = 2;</code>
   */
  ResultEntriesOrBuilder getResultsOrBuilder();
}
