// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: recommendation.proto

package com.mindspore.ide.toolkit.protomessage;

/**
 * <pre>
 * The response message containing the greetings
 * </pre>
 *
 * Protobuf type {@code proto.CompleteReply}
 */
public  final class CompleteReply extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:proto.CompleteReply)
    CompleteReplyOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CompleteReply.newBuilder() to construct.
  private CompleteReply(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CompleteReply() {
    oldPrefix_ = "";
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private CompleteReply(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            String s = input.readStringRequireUtf8();

            oldPrefix_ = s;
            break;
          }
          case 18: {
            ResultEntries.Builder subBuilder = null;
            if (results_ != null) {
              subBuilder = results_.toBuilder();
            }
            results_ = input.readMessage(ResultEntries.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(results_);
              results_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return CodeCompletionProto.internal_static_proto_CompleteReply_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return CodeCompletionProto.internal_static_proto_CompleteReply_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            CompleteReply.class, Builder.class);
  }

  public static final int OLD_PREFIX_FIELD_NUMBER = 1;
  private volatile Object oldPrefix_;
  /**
   * <code>string old_prefix = 1;</code>
   */
  public String getOldPrefix() {
    Object ref = oldPrefix_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      oldPrefix_ = s;
      return s;
    }
  }
  /**
   * <code>string old_prefix = 1;</code>
   */
  public com.google.protobuf.ByteString
      getOldPrefixBytes() {
    Object ref = oldPrefix_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      oldPrefix_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int RESULTS_FIELD_NUMBER = 2;
  private ResultEntries results_;
  /**
   * <code>.proto.ResultEntries results = 2;</code>
   */
  public boolean hasResults() {
    return results_ != null;
  }
  /**
   * <code>.proto.ResultEntries results = 2;</code>
   */
  public ResultEntries getResults() {
    return results_ == null ? ResultEntries.getDefaultInstance() : results_;
  }
  /**
   * <code>.proto.ResultEntries results = 2;</code>
   */
  public ResultEntriesOrBuilder getResultsOrBuilder() {
    return getResults();
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getOldPrefixBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, oldPrefix_);
    }
    if (results_ != null) {
      output.writeMessage(2, getResults());
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getOldPrefixBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, oldPrefix_);
    }
    if (results_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getResults());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof CompleteReply)) {
      return super.equals(obj);
    }
    CompleteReply other = (CompleteReply) obj;

    if (!getOldPrefix()
        .equals(other.getOldPrefix())) return false;
    if (hasResults() != other.hasResults()) return false;
    if (hasResults()) {
      if (!getResults()
          .equals(other.getResults())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + OLD_PREFIX_FIELD_NUMBER;
    hash = (53 * hash) + getOldPrefix().hashCode();
    if (hasResults()) {
      hash = (37 * hash) + RESULTS_FIELD_NUMBER;
      hash = (53 * hash) + getResults().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static CompleteReply parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static CompleteReply parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static CompleteReply parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static CompleteReply parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static CompleteReply parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static CompleteReply parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static CompleteReply parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static CompleteReply parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static CompleteReply parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static CompleteReply parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static CompleteReply parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static CompleteReply parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(CompleteReply prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * The response message containing the greetings
   * </pre>
   *
   * Protobuf type {@code proto.CompleteReply}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:proto.CompleteReply)
      CompleteReplyOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return CodeCompletionProto.internal_static_proto_CompleteReply_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return CodeCompletionProto.internal_static_proto_CompleteReply_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              CompleteReply.class, Builder.class);
    }

    // Construct using com.mindspore.ide.toolkit.protomessage.CompleteReply.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      oldPrefix_ = "";

      if (resultsBuilder_ == null) {
        results_ = null;
      } else {
        results_ = null;
        resultsBuilder_ = null;
      }
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return CodeCompletionProto.internal_static_proto_CompleteReply_descriptor;
    }

    @Override
    public CompleteReply getDefaultInstanceForType() {
      return CompleteReply.getDefaultInstance();
    }

    @Override
    public CompleteReply build() {
      CompleteReply result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public CompleteReply buildPartial() {
      CompleteReply result = new CompleteReply(this);
      result.oldPrefix_ = oldPrefix_;
      if (resultsBuilder_ == null) {
        result.results_ = results_;
      } else {
        result.results_ = resultsBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof CompleteReply) {
        return mergeFrom((CompleteReply)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(CompleteReply other) {
      if (other == CompleteReply.getDefaultInstance()) return this;
      if (!other.getOldPrefix().isEmpty()) {
        oldPrefix_ = other.oldPrefix_;
        onChanged();
      }
      if (other.hasResults()) {
        mergeResults(other.getResults());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      CompleteReply parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (CompleteReply) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private Object oldPrefix_ = "";
    /**
     * <code>string old_prefix = 1;</code>
     */
    public String getOldPrefix() {
      Object ref = oldPrefix_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        oldPrefix_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string old_prefix = 1;</code>
     */
    public com.google.protobuf.ByteString
        getOldPrefixBytes() {
      Object ref = oldPrefix_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        oldPrefix_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string old_prefix = 1;</code>
     */
    public Builder setOldPrefix(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      oldPrefix_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string old_prefix = 1;</code>
     */
    public Builder clearOldPrefix() {
      
      oldPrefix_ = getDefaultInstance().getOldPrefix();
      onChanged();
      return this;
    }
    /**
     * <code>string old_prefix = 1;</code>
     */
    public Builder setOldPrefixBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      oldPrefix_ = value;
      onChanged();
      return this;
    }

    private ResultEntries results_;
    private com.google.protobuf.SingleFieldBuilderV3<
        ResultEntries, ResultEntries.Builder, ResultEntriesOrBuilder> resultsBuilder_;
    /**
     * <code>.proto.ResultEntries results = 2;</code>
     */
    public boolean hasResults() {
      return resultsBuilder_ != null || results_ != null;
    }
    /**
     * <code>.proto.ResultEntries results = 2;</code>
     */
    public ResultEntries getResults() {
      if (resultsBuilder_ == null) {
        return results_ == null ? ResultEntries.getDefaultInstance() : results_;
      } else {
        return resultsBuilder_.getMessage();
      }
    }
    /**
     * <code>.proto.ResultEntries results = 2;</code>
     */
    public Builder setResults(ResultEntries value) {
      if (resultsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        results_ = value;
        onChanged();
      } else {
        resultsBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.proto.ResultEntries results = 2;</code>
     */
    public Builder setResults(
        ResultEntries.Builder builderForValue) {
      if (resultsBuilder_ == null) {
        results_ = builderForValue.build();
        onChanged();
      } else {
        resultsBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.proto.ResultEntries results = 2;</code>
     */
    public Builder mergeResults(ResultEntries value) {
      if (resultsBuilder_ == null) {
        if (results_ != null) {
          results_ =
            ResultEntries.newBuilder(results_).mergeFrom(value).buildPartial();
        } else {
          results_ = value;
        }
        onChanged();
      } else {
        resultsBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.proto.ResultEntries results = 2;</code>
     */
    public Builder clearResults() {
      if (resultsBuilder_ == null) {
        results_ = null;
        onChanged();
      } else {
        results_ = null;
        resultsBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.proto.ResultEntries results = 2;</code>
     */
    public ResultEntries.Builder getResultsBuilder() {
      
      onChanged();
      return getResultsFieldBuilder().getBuilder();
    }
    /**
     * <code>.proto.ResultEntries results = 2;</code>
     */
    public ResultEntriesOrBuilder getResultsOrBuilder() {
      if (resultsBuilder_ != null) {
        return resultsBuilder_.getMessageOrBuilder();
      } else {
        return results_ == null ?
            ResultEntries.getDefaultInstance() : results_;
      }
    }
    /**
     * <code>.proto.ResultEntries results = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        ResultEntries, ResultEntries.Builder, ResultEntriesOrBuilder>
        getResultsFieldBuilder() {
      if (resultsBuilder_ == null) {
        resultsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            ResultEntries, ResultEntries.Builder, ResultEntriesOrBuilder>(
                getResults(),
                getParentForChildren(),
                isClean());
        results_ = null;
      }
      return resultsBuilder_;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:proto.CompleteReply)
  }

  // @@protoc_insertion_point(class_scope:proto.CompleteReply)
  private static final CompleteReply DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new CompleteReply();
  }

  public static CompleteReply getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CompleteReply>
      PARSER = new com.google.protobuf.AbstractParser<CompleteReply>() {
    @Override
    public CompleteReply parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new CompleteReply(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<CompleteReply> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<CompleteReply> getParserForType() {
    return PARSER;
  }

  @Override
  public CompleteReply getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

