// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: recommendation.proto

package com.mindspore.ide.toolkit.protomessage;

public interface CompleteRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.CompleteRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string prefix = 1;</code>
   */
  String getPrefix();
  /**
   * <code>string prefix = 1;</code>
   */
  com.google.protobuf.ByteString
      getPrefixBytes();

  /**
   * <code>string before = 2;</code>
   */
  String getBefore();
  /**
   * <code>string before = 2;</code>
   */
  com.google.protobuf.ByteString
      getBeforeBytes();

  /**
   * <code>string after = 3;</code>
   */
  String getAfter();
  /**
   * <code>string after = 3;</code>
   */
  com.google.protobuf.ByteString
      getAfterBytes();
}
