// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: recommendation.proto

package com.mindspore.ide.toolkit.protomessage;

public interface ResultEntryOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.ResultEntry)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string new_prefix = 1;</code>
   */
  String getNewPrefix();
  /**
   * <code>string new_prefix = 1;</code>
   */
  com.google.protobuf.ByteString
      getNewPrefixBytes();

  /**
   * <code>string details = 2;</code>
   */
  String getDetails();
  /**
   * <code>string details = 2;</code>
   */
  com.google.protobuf.ByteString
      getDetailsBytes();
}
