// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: recommendation.proto

package com.mindspore.ide.toolkit.protomessage;

public interface ResultEntriesOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.ResultEntries)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .proto.ResultEntry resultEntry = 1;</code>
   */
  java.util.List<ResultEntry>
      getResultEntryList();
  /**
   * <code>repeated .proto.ResultEntry resultEntry = 1;</code>
   */
  ResultEntry getResultEntry(int index);
  /**
   * <code>repeated .proto.ResultEntry resultEntry = 1;</code>
   */
  int getResultEntryCount();
  /**
   * <code>repeated .proto.ResultEntry resultEntry = 1;</code>
   */
  java.util.List<? extends ResultEntryOrBuilder>
      getResultEntryOrBuilderList();
  /**
   * <code>repeated .proto.ResultEntry resultEntry = 1;</code>
   */
  ResultEntryOrBuilder getResultEntryOrBuilder(
      int index);
}
