// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: recommendation.proto

package com.mindspore.ide.toolkit.protomessage;

/**
 * Protobuf type {@code proto.ResultEntries}
 */
public  final class ResultEntries extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:proto.ResultEntries)
    ResultEntriesOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ResultEntries.newBuilder() to construct.
  private ResultEntries(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ResultEntries() {
    resultEntry_ = java.util.Collections.emptyList();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ResultEntries(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              resultEntry_ = new java.util.ArrayList<ResultEntry>();
              mutable_bitField0_ |= 0x00000001;
            }
            resultEntry_.add(
                input.readMessage(ResultEntry.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        resultEntry_ = java.util.Collections.unmodifiableList(resultEntry_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return CodeCompletionProto.internal_static_proto_ResultEntries_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return CodeCompletionProto.internal_static_proto_ResultEntries_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ResultEntries.class, Builder.class);
  }

  public static final int RESULTENTRY_FIELD_NUMBER = 1;
  private java.util.List<ResultEntry> resultEntry_;
  /**
   * <code>repeated .proto.ResultEntry resultEntry = 1;</code>
   */
  public java.util.List<ResultEntry> getResultEntryList() {
    return resultEntry_;
  }
  /**
   * <code>repeated .proto.ResultEntry resultEntry = 1;</code>
   */
  public java.util.List<? extends ResultEntryOrBuilder>
      getResultEntryOrBuilderList() {
    return resultEntry_;
  }
  /**
   * <code>repeated .proto.ResultEntry resultEntry = 1;</code>
   */
  public int getResultEntryCount() {
    return resultEntry_.size();
  }
  /**
   * <code>repeated .proto.ResultEntry resultEntry = 1;</code>
   */
  public ResultEntry getResultEntry(int index) {
    return resultEntry_.get(index);
  }
  /**
   * <code>repeated .proto.ResultEntry resultEntry = 1;</code>
   */
  public ResultEntryOrBuilder getResultEntryOrBuilder(
      int index) {
    return resultEntry_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < resultEntry_.size(); i++) {
      output.writeMessage(1, resultEntry_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < resultEntry_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, resultEntry_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ResultEntries)) {
      return super.equals(obj);
    }
    ResultEntries other = (ResultEntries) obj;

    if (!getResultEntryList()
        .equals(other.getResultEntryList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getResultEntryCount() > 0) {
      hash = (37 * hash) + RESULTENTRY_FIELD_NUMBER;
      hash = (53 * hash) + getResultEntryList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ResultEntries parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ResultEntries parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ResultEntries parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ResultEntries parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ResultEntries parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ResultEntries parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ResultEntries parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ResultEntries parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ResultEntries parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ResultEntries parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ResultEntries parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ResultEntries parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ResultEntries prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code proto.ResultEntries}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:proto.ResultEntries)
      ResultEntriesOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return CodeCompletionProto.internal_static_proto_ResultEntries_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return CodeCompletionProto.internal_static_proto_ResultEntries_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ResultEntries.class, Builder.class);
    }

    // Construct using com.mindspore.ide.toolkit.protomessage.ResultEntries.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getResultEntryFieldBuilder();
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      if (resultEntryBuilder_ == null) {
        resultEntry_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        resultEntryBuilder_.clear();
      }
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return CodeCompletionProto.internal_static_proto_ResultEntries_descriptor;
    }

    @Override
    public ResultEntries getDefaultInstanceForType() {
      return ResultEntries.getDefaultInstance();
    }

    @Override
    public ResultEntries build() {
      ResultEntries result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public ResultEntries buildPartial() {
      ResultEntries result = new ResultEntries(this);
      int from_bitField0_ = bitField0_;
      if (resultEntryBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          resultEntry_ = java.util.Collections.unmodifiableList(resultEntry_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.resultEntry_ = resultEntry_;
      } else {
        result.resultEntry_ = resultEntryBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ResultEntries) {
        return mergeFrom((ResultEntries)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ResultEntries other) {
      if (other == ResultEntries.getDefaultInstance()) return this;
      if (resultEntryBuilder_ == null) {
        if (!other.resultEntry_.isEmpty()) {
          if (resultEntry_.isEmpty()) {
            resultEntry_ = other.resultEntry_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureResultEntryIsMutable();
            resultEntry_.addAll(other.resultEntry_);
          }
          onChanged();
        }
      } else {
        if (!other.resultEntry_.isEmpty()) {
          if (resultEntryBuilder_.isEmpty()) {
            resultEntryBuilder_.dispose();
            resultEntryBuilder_ = null;
            resultEntry_ = other.resultEntry_;
            bitField0_ = (bitField0_ & ~0x00000001);
            resultEntryBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getResultEntryFieldBuilder() : null;
          } else {
            resultEntryBuilder_.addAllMessages(other.resultEntry_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ResultEntries parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ResultEntries) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<ResultEntry> resultEntry_ =
      java.util.Collections.emptyList();
    private void ensureResultEntryIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        resultEntry_ = new java.util.ArrayList<ResultEntry>(resultEntry_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        ResultEntry, ResultEntry.Builder, ResultEntryOrBuilder> resultEntryBuilder_;

    /**
     * <code>repeated .proto.ResultEntry resultEntry = 1;</code>
     */
    public java.util.List<ResultEntry> getResultEntryList() {
      if (resultEntryBuilder_ == null) {
        return java.util.Collections.unmodifiableList(resultEntry_);
      } else {
        return resultEntryBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .proto.ResultEntry resultEntry = 1;</code>
     */
    public int getResultEntryCount() {
      if (resultEntryBuilder_ == null) {
        return resultEntry_.size();
      } else {
        return resultEntryBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .proto.ResultEntry resultEntry = 1;</code>
     */
    public ResultEntry getResultEntry(int index) {
      if (resultEntryBuilder_ == null) {
        return resultEntry_.get(index);
      } else {
        return resultEntryBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .proto.ResultEntry resultEntry = 1;</code>
     */
    public Builder setResultEntry(
        int index, ResultEntry value) {
      if (resultEntryBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureResultEntryIsMutable();
        resultEntry_.set(index, value);
        onChanged();
      } else {
        resultEntryBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .proto.ResultEntry resultEntry = 1;</code>
     */
    public Builder setResultEntry(
        int index, ResultEntry.Builder builderForValue) {
      if (resultEntryBuilder_ == null) {
        ensureResultEntryIsMutable();
        resultEntry_.set(index, builderForValue.build());
        onChanged();
      } else {
        resultEntryBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .proto.ResultEntry resultEntry = 1;</code>
     */
    public Builder addResultEntry(ResultEntry value) {
      if (resultEntryBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureResultEntryIsMutable();
        resultEntry_.add(value);
        onChanged();
      } else {
        resultEntryBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .proto.ResultEntry resultEntry = 1;</code>
     */
    public Builder addResultEntry(
        int index, ResultEntry value) {
      if (resultEntryBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureResultEntryIsMutable();
        resultEntry_.add(index, value);
        onChanged();
      } else {
        resultEntryBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .proto.ResultEntry resultEntry = 1;</code>
     */
    public Builder addResultEntry(
        ResultEntry.Builder builderForValue) {
      if (resultEntryBuilder_ == null) {
        ensureResultEntryIsMutable();
        resultEntry_.add(builderForValue.build());
        onChanged();
      } else {
        resultEntryBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .proto.ResultEntry resultEntry = 1;</code>
     */
    public Builder addResultEntry(
        int index, ResultEntry.Builder builderForValue) {
      if (resultEntryBuilder_ == null) {
        ensureResultEntryIsMutable();
        resultEntry_.add(index, builderForValue.build());
        onChanged();
      } else {
        resultEntryBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .proto.ResultEntry resultEntry = 1;</code>
     */
    public Builder addAllResultEntry(
        Iterable<? extends ResultEntry> values) {
      if (resultEntryBuilder_ == null) {
        ensureResultEntryIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, resultEntry_);
        onChanged();
      } else {
        resultEntryBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .proto.ResultEntry resultEntry = 1;</code>
     */
    public Builder clearResultEntry() {
      if (resultEntryBuilder_ == null) {
        resultEntry_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        resultEntryBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .proto.ResultEntry resultEntry = 1;</code>
     */
    public Builder removeResultEntry(int index) {
      if (resultEntryBuilder_ == null) {
        ensureResultEntryIsMutable();
        resultEntry_.remove(index);
        onChanged();
      } else {
        resultEntryBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .proto.ResultEntry resultEntry = 1;</code>
     */
    public ResultEntry.Builder getResultEntryBuilder(
        int index) {
      return getResultEntryFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .proto.ResultEntry resultEntry = 1;</code>
     */
    public ResultEntryOrBuilder getResultEntryOrBuilder(
        int index) {
      if (resultEntryBuilder_ == null) {
        return resultEntry_.get(index);  } else {
        return resultEntryBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .proto.ResultEntry resultEntry = 1;</code>
     */
    public java.util.List<? extends ResultEntryOrBuilder>
         getResultEntryOrBuilderList() {
      if (resultEntryBuilder_ != null) {
        return resultEntryBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(resultEntry_);
      }
    }
    /**
     * <code>repeated .proto.ResultEntry resultEntry = 1;</code>
     */
    public ResultEntry.Builder addResultEntryBuilder() {
      return getResultEntryFieldBuilder().addBuilder(
          ResultEntry.getDefaultInstance());
    }
    /**
     * <code>repeated .proto.ResultEntry resultEntry = 1;</code>
     */
    public ResultEntry.Builder addResultEntryBuilder(
        int index) {
      return getResultEntryFieldBuilder().addBuilder(
          index, ResultEntry.getDefaultInstance());
    }
    /**
     * <code>repeated .proto.ResultEntry resultEntry = 1;</code>
     */
    public java.util.List<ResultEntry.Builder>
         getResultEntryBuilderList() {
      return getResultEntryFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        ResultEntry, ResultEntry.Builder, ResultEntryOrBuilder>
        getResultEntryFieldBuilder() {
      if (resultEntryBuilder_ == null) {
        resultEntryBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            ResultEntry, ResultEntry.Builder, ResultEntryOrBuilder>(
                resultEntry_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        resultEntry_ = null;
      }
      return resultEntryBuilder_;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:proto.ResultEntries)
  }

  // @@protoc_insertion_point(class_scope:proto.ResultEntries)
  private static final ResultEntries DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ResultEntries();
  }

  public static ResultEntries getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ResultEntries>
      PARSER = new com.google.protobuf.AbstractParser<ResultEntries>() {
    @Override
    public ResultEntries parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ResultEntries(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ResultEntries> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<ResultEntries> getParserForType() {
    return PARSER;
  }

  @Override
  public ResultEntries getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

